export const genreImages: { [key: string]: string } = {
  action: "src/assets/genres/action.jpg",
  adventure: "src/assets/genres/adventure.jpg",
  animation: "src/assets/genres/animation.jpg",
  comedy: "src/assets/genres/comedy.jpg",
  crime: "src/assets/genres/crime.jpg",
  documentary: "src/assets/genres/documentary.jpg",
  drama: "src/assets/genres/drama.jpg",
  family: "src/assets/genres/family.jpg",
  fantasy: "src/assets/genres/fantasy.jpg",
  history: "src/assets/genres/history.jpg",
  horror: "src/assets/genres/horror.jpg",
  music: "src/assets/genres/music.jpg",
  mystery: "src/assets/genres/mystery.jpg",
  romance: "src/assets/genres/romance.jpg",
  scifi: "src/assets/genres/scifi.jpg",
  "stand-up": "src/assets/genres/stand-up.jpg",
  thriller: "src/assets/genres/thriller.jpg",
  "tv-movie": "src/assets/genres/tv-movie.jpg",
  war: "src/assets/genres/war.jpg",
  western: "src/assets/genres/western.jpg",
};